const personalPlant = [
  {
    id: "plant_1",
    image: "plantImage-1.png",
    category: "Outdoor",
    name: "Tomato",
    duration: "1 month 3 days",
    temperature: 20,
    alert: "You haven’t watered this plant!",
    active: false,
    icon: "bell",
    button: true,
  },
  {
    id: "plant_2",
    image: "plantImage-2.png",
    category: "Outdoor",
    name: "Chili",
    duration: "2 months 23 days",
    temperature: 20,
    alert: "You haven’t watered this plant!",
    active: false,
    icon: "bell",
    button: true,
  },
  {
    id: "plant_3",
    image: "plantImage-2.png",
    category: "Outdoor",
    name: "Cherry",
    duration: "1 year 2 months 3 days",
    temperature: 20,
    alert: "You haven’t watered this plant!",
    active: false,
    icon: "bell",
    button: true,
  },
  {
    id: "plant_4",
    image: "plantImage-2.png",
    category: "Outdoor",
    name: "Cherry",
    duration: "1 year 2 months 3 days",
    temperature: 20,
    alert: "You haven’t watered this plant!",
    active: false,
    icon: "bell",
    button: true,
  },
  {
    id: "plant_5",
    image: "plantImage-2.png",
    category: "Outdoor",
    name: "Cherry",
    duration: "1 year 2 months 3 days",
    temperature: 20,
    alert: "You haven’t watered this plant!",
    active: false,
    icon: "bell",
    button: true,
  },
  {
    id: "plant_6",
    image: "plantImage-2.png",
    category: "Outdoor",
    name: "Basil Leaves",
    duration: "1 year 2 months 3 days",
    temperature: 50,
    alert: "You have watered this field!",
    icon: "tick",
    active: false,
    button: false,
  },
];

export default personalPlant;
