"""empty message

Revision ID: 87e5d4b1c347
Revises: 
Create Date: 2024-04-11 11:58:40.006559

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '87e5d4b1c347'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('accounts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('prefix', sa.String(length=255), default='ACC', nullable=False))

    with op.batch_alter_table('farms', schema=None) as batch_op:
        batch_op.add_column(sa.Column('prefix', sa.String(length=255),default='FRM', nullable=False))

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('prefix', sa.String(length=255),default='USR', nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('prefix')

    with op.batch_alter_table('farms', schema=None) as batch_op:
        batch_op.drop_column('prefix')

    with op.batch_alter_table('accounts', schema=None) as batch_op:
        batch_op.drop_column('prefix')

    # ### end Alembic commands ###
